<a href="https://colab.research.google.com/github/simongiando/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## In this notebook, we're going to cover some of the most fundamental concepts of tensors using tensor flow


More specifically, we're goint to cvoer:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Excercises to try for yourself!

In [2]:
# Introtuction to Tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print (tf.__version__)

2.8.2


In [4]:
# Creating tensors with tf.constant()
scalar = tf.constant (7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the dimension of our vector
vector.ndim

1

In [8]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) # Specify the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# What's the number dimensions of another matix?
another_matrix.ndim

2

In [12]:
# Let's create a tensors
tensor = tf.constant ([[[1,2,3,],
                         [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number 
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: n-dimensional array of number (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector) 

### Creating tensors with 'tf.Variable'

In [16]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant ([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# Lets try change one of the elemets in our changeable tensor
changeable_tensor [0] =7
changeable_tensor

TypeError: ignored

In [18]:
# how about we try .assign()
changeable_tensor [0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
# Lets try change our unchangeable tensor
unchangeable_tensor [0].assign(7)
unchangeable_tensor

AttributeError: ignored

**Note:** Rarely in practice will you kneed to decide whether to use 'tf.constant' or 'tf.Variable' to create tensors, as TensorFlow does this for you. However, if in doubt, use 'tf.constant' and change it later if needed

## Creating random tensor

Random tensors are tensors of some abitrary size which contain random numbers

In [20]:
# Crea two random (but the same) sensors
random_1 = tf.random.Generator.from_seed (7) # set seed for reproducibility
random_1 = random_1.normal (shape=(3,2))
random_2 = tf.random.Generator.from_seed (7)
random_2 = random_2.normal (shape=(3,2))

# Area they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of the elements in the tensor

In [21]:
# Shuffle a tensor (valueable for when you wanto to shuffle your data so the ineherent order doesn't effect learning)
not_shuffled = tf.constant ([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [23]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise** Read through TensorFlow documentation on random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them

> Rule No.4 It looks like if we want our shuffled tensors to be in the same order, we've got to use the global random seed as well as the operation level random seed:


In [24]:
tf.random.set_seed(5)
tf.random.shuffle (not_shuffled,seed=5)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [25]:
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled,seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [26]:
## Create a tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumpY arrays into tensors

the main difference between NumPy arrays and TensorFlow tensors is that
tensors can be run on a GPU with (faster computing)

In [28]:
# You can also turn numpy
import numpy as np
numpy_A = np.arange (1,25,dtype=np.int32) # Create a NumPy array between 1 and 25
numpy_A

# x = tf.constant (some_matrix) # capital for matrix or tensor
# y = tf.constant (vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant (numpy_A,shape=(2,3,4))
B = tf.constant (numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [30]:
A = tf.constant (numpy_A, shape=(2,4,3))
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [31]:
A = tf.constant (numpy_A,shape= (2,6,2))
A

<tf.Tensor: shape=(2, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [32]:
A = tf.constant (numpy_A, shape = (3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

### Getting Information from tensors

When dealing with tensor you probably to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [33]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor [0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [35]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [36]:
# Get various attributes of our tensor
print ("Datatype of every element:", rank_4_tensor.dtype)
print ("Number of dimensions:", rank_4_tensor.ndim)
print ("Shape of tensor:", rank_4_tensor.shape)
print ("Elements along the 0 axis:",rank_4_tensor.shape[0])
print ("Elements along the last axis:", rank_4_tensor.shape [-1])
print ("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print ("Total number of elements in our tensor in NumPy:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor in NumPy: 120


## Indexing tensors
Tensors can be indexed just like Python lists

In [38]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [39]:
# Get the first 2 elements of each dimension 
rank_4_tensor [:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [40]:
some_list[:1]

[1]

In [46]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [51]:
# Get the first element each dimension from each index expect for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [56]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],
                  [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [57]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [59]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [62]:
# get the last item of each of row of our rank 2 tensor
rank_2_tensor  [:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [65]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [66]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]

In [69]:
# Alternative to tf.newaxis
tf.expand_dims (rank_2_tensor,axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [71]:
tf.expand_dims (rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [72]:
tf.expand_dims (rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)
** Basic operations**

`+`, `-`,`*`,`/`

In [74]:
# You can add values to a tensor using the addition operator
tensor = tf.constant ([[10,7],
                       [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [76]:
# Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [77]:
# Substraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [78]:
# We can use the tensor flow built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix Multiplication

In machine learning, matrix multiplication is one of the most common

two rules for tensors

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer side

In [81]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [82]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [83]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [85]:
# Create a tensor (3,2)
x = tf.constant ([[1,2],
                 [3,4],
                 [4,5]])
# Create another tensor (3,2)
y = tf.constant ([[7,8,],
                  [9,10],
                  [11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [87]:
# Try to matrix multiply tensors of same shape
tf.matmul(x,y)

InvalidArgumentError: ignored

In [89]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [88]:
# Let's change the shape of Y
tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [93]:
x.shape, tf.reshape(y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [94]:
# Try to multiply x by reshaped Y
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [61, 68, 75],
       [78, 87, 96]], dtype=int32)>

In [97]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [61, 68, 75],
       [78, 87, 96]], dtype=int32)>

In [100]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [119, 132]], dtype=int32)>

In [102]:
tf.reshape(x,shape=(2,3)).shape,y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [104]:
# Can do the same with transpose
x,tf.transpose(x), tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 4],
        [2, 4, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 4, 5]], dtype=int32)>)

In [105]:
# Try matrix multiplication rather than reshape
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78,  86],
       [105, 116]], dtype=int32)>

📑 **Resource:** Info and example of matrix multiplication
[link text](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

** The dot Product **

Matrix multiplication is also refereed to as the dot product.

you can perform matrix multiplication using:

*`tf.matmul()`
*`tf.tensordot()`
*`@`

In [110]:
# Perform the dot product on x and y (requires x or y tobe transposed)
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78,  86],
       [105, 116]], dtype=int32)>

In [111]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 68,  86, 104]], dtype=int32)>

In [113]:
# Perform matrix multiplication between x and y (reshaped)
tf.matmul(x, tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [61, 68, 75],
       [78, 87, 96]], dtype=int32)>

In [116]:
# Check the values of y, reshape and transposed y
print ("Normal Y:")
print (y,"\n") # "\n" to add new line

print ('Y Reshaped to, (2,3):')
print (tf.reshape(y,(2,3)),'\n')

print ('Y Transposed:')
print (tf.transpose(y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y Reshaped to, (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y Transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [118]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 68,  86, 104]], dtype=int32)>

Generally, when performong matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose rather reshape one of the tensors to get satisfied the matrix multiplication rules